### ISSUE TITLE
Codable Support

### ISSUE THREAD

**Issue by pedrosilva88** [apple/swift-collections#12]
I was trying to use the OrderedDictionary in a Codable struct.
I have some API requests that I receive a few dictionaries and I would like to preserve that order.
Previously I have a property like this.

`let foos: [String: Foo]`

And the parse works just fine, but the order of the items isn't guaranteed.

So I changed to this,

`let foos: OrderedDictionary<String, Foo>`

and I get this error.

```
"Expected to decode Array<Any> but found a dictionary instead."
```

It would be great if you give support Codable parsing.

**Comment by bmarkowitz** [comment]
I could certainly be wrong (I haven't tried it out yet), but it does appear as though there's Codable support already.

For example, see: 

Sources > OrderedCollections > OrderedDictionary > OrderedDictionary+Codable.swift

**Comment by pedrosilva88** [comment]
```
public init(from decoder: Decoder) throws {
    // We expect to be encoded as an array of alternating key-value pairs.
    var container = try decoder.unkeyedContainer()
...
```

The initialization from a decoder expects to receive an Array, instead of a dictionary.
Do you have any solution for this situation that I'm not looking?

**Comment by bmarkowitz** [comment]
Alright, so I just got around to trying this out, and Codable support is already included. 

However, it probably doesn't work how you're expecting it does. If you check out the docs for the Codable support at the file path I provided in my last comment (Sources > OrderedCollections > OrderedDictionary > OrderedDictionary+Codable.swift), and if you go to the docs of the encode() function, you'll see this note:

```
- Note: Unlike the standard `Dictionary` type, ordered dictionaries
  ///    always encode in an unkeyed container, because `Codable`'s keyed
  ///    containers do not guarantee that they preserve the ordering of the
  ///    items they contain. (And in popular encoding formats, keyed containers
  ///    tend to map to unordered data structures -- e.g., JSON's "object"
  ///    construct is explicitly unordered.)
```

... and then there's another comment in the decode() function:

`// Encode contents as an array of alternating key-value pairs.`

... which means your JSON needs to look something like this:

```
{
    "foos": ["bar", "bar"]
}
```

I went ahead and put together a quick playground that makes a call to a mock API that returns that JSON, and this is what worked:

```
import Cocoa
import Collections

struct SampleResponse: Codable {
    let foos: OrderedDictionary<String, String>
}

//This mock API has the following JSON:
// {
//   "foos": ["bar", "baz"]
// }
let dataTask = URLSession.shared.dataTask(with: URLRequest(url: URL(string: "https://run.mocky.io/v3/3ba2d077-c2a9-4894-8b8b-07efc514de76")!)) {
    (data: Data?, response: URLResponse?, error: Error?) in
    
    let decodedResponse = try! JSONDecoder().decode(SampleResponse.self, from: data!)
    
    print(decodedResponse) //prints: SampleResponse(foos: OrderedDictionary<String, String>(["bar": "bar"]))
}

dataTask.resume()
```

Because the decode method attempts to match up a key with a value, you'll notice that you need to have an even number of items in the JSON array, or else you'll get a runtime error from Swift saying the data is corrupted ("Unkeyed container reached end before value in key-value pair").

**Comment by pedrosilva88** [comment]
Yes, I noticed that.
Unfortunately this doesn't resolve my problem, because I can't change the response from the service.
I hope they found a solution for this problem. Maybe there will be more people raising this.

Thanks anyway for the explanation and the help.

**Comment by lorentey** [comment]
`OrderedDictionary` needs to encode itself as an array of alternating keys and values, because keyed encoders/decoders aren't order-preserving. This is unavoidable, because the underlying encoding formats aren't order-preserving, either. For example, this is how [json.org](https://www.json.org/json-en.html) defines its objects: (bold highlight from me)

> An *object* is an **unordered** set of name/value pairs. 

It would be possible(*) to allow string-keyed ordered dictionaries to *decode* themselves from a keyed container. But I strongly suspect that it would just lead to even more serious problems, by resulting in the data getting unexpectedly (and quietly!) serialized into a different format.

<small>\* The caveat is that implementing another decoder path runs into the problem that the `Decoder` protocol doesn't explicitly require that decoder instances remain usable after they throw an error. Still, this implicit requirement seems to be universally followed.</small>

If you don't mind that the order of items may be scrambled during serialization/deserialization, then it would probably be a better idea to just continue using `Dictionary` instead. (`OrderedDictionary` is not a replacement to `Dictionary` -- it's complementary.) However, if you have some other reason to choose an ordered collection (e.g., the order only matters while the data is in memory), then I recommend explicitly converting the data into a `Dictionary` before/after serialization/deserialization. Another option is to write a simple adapter type that wraps an `OrderedDictionary` and implements `Codable` differently.

Even though `OrderedDictionary` cannot encode itself into a JSON object, it would be very much useful to write a JSON decoder/encoder that does preserve the original order of the items in these constructs. This would help in cases where servers violate the JSON "specification" and expect the name/value pairs to have a particular ordering in the encoded text.

**Comment by lorentey** [comment]
The encoding format is noted in the [documentation of `OrderedDictionary.encode(to:)`](https://github.com/apple/swift-collections/blob/0.0.1/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary%2BCodable.swift#L13-L28), but the same note is currently missing from the decoding initializer. We should fix that!

**Comment by lorentey** [comment]
PR #26 updates the documentation of the `init(from:)` initializer to highlight the expected encoding format, resolving this issue.

As noted above, changing the `Decodable` implementation to accept keyed containers would turn an obvious runtime issue (with a straightforward workaround) into a silent serialization format change, which would be an unacceptable outcome. 

(If we did that, replacing a `Dictionary` with `OrderedDictionary` in existing code would allow previously encoded archives to be read, but it would have the (very disruptive) side effect that newly encoded data would silently start using a different format -- breaking interoperability. It's better to refuse to load unexpected formats at all.)
