### ISSUE TITLE
Move Documentation into swift-docc format

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-collections#134]
Move the current Documentation folder content into the Sources/* folder's *.docc to fit swift-docc.

It can provide a better documentation when used in Xcode and later be hosted on a website.

The tutorial file can be added later.

**Comment by lorentey** [comment]
Yes, we should use docc for documentation.

Note that some/most of the docs under the Documentation folder are API documentation extracts that are duplicated in doc comments -- instead of simply moving the files, it would probably make more sense to just update the original doc comments to make sure they follow docc's conventions.

Until we have a website that hosts generated documentation, the Documentation/*.md files are still useful for reference/overview purposes, and we should probably keep them.

**Comment by kelvin13** [comment]
swiftinit currently hosts this package’s documentation here: https://swiftinit.org/reference/swift-collections

**Comment by lorentey** [comment]
We actually shipped DocC bundles in 1.0.4 with https://github.com/apple/swift-collections/pull/252!
