### ISSUE TITLE
How do I get a OrderedDictionary from plist or xml from PropertyListSerialization or other Decoder?

### ISSUE THREAD

**Issue by miku1958** [apple/swift-collections#135]
I wish there was a more convenient way to convert xml/plist to OrderedDictionary.

Thanks!

**Comment by lorentey** [comment]
`OrderedDictionary` does conform to `Codable` -- it is trivial to encode/decode it to/from popular serialization formats. It  encodes itself as an array of key-value pairs, as that is the only way to reliably preserve the ordering of its contents.

Unfortunately `OrderedDictionary` cannot use unkeyed decoders/encoders for serialization, because those containers don't guarantee to preserve the ordering of items. (Reflecting the behavior of the underlying JSON/plist/etc encoders/decoders.)

https://github.com/apple/swift-collections/issues/12#issuecomment-816277180 has some more information as well as suggestions what to do if you need to load an OrderedDictionary from an unkeyed container.

**Comment by lorentey** [comment]
(For getting ordered dictionaries in & out of `PropertyListSerialization`, the big issue is that `OrderedDictionary` isn't a plist type, and it isn't feasible to add direct support for it without breaking compatibility with untold amounts of existing code. `Codable` is explicitly designed to support converting arbitrary data to/from plist format -- I recommend using it instead of directly using `PropertyListSerialization`.)

**Comment by Jeehut** [comment]
@lorentey While I understand the point you're trying to make here (and I've also read your linked comment), I have to disagree that the current state is "correct" and this issue can just be closed. Your point is that some of the formats (and you're quoting JSON in your comment) are not ordered as per the specification. But the OP was asking for plists in particular, which is also my use case right now as I'm trying to parse a `.stringsdict` file. And order is pretty important in XML files (such as a plist file). In my use case, I'm trying to read translations from `.stringsdict` files to make them editable with a nice UI, then writing the adjusted entries back to a file. And I don't want my users to see any changes in order from the original file, because it's important that they can easily spot the changes in the file (in Git diffs), without being distracted from random order changes.

From a type that calls itself "ordered dictionary" I would expect that it's interchangeable with a "dictionary" in a `PropertyListDecoder` context and that it also encodes back into a dictionary (not an array). So, the very fact that this type serializes as an array is very confusing given its name. It doesn't provide much benefit over an array of pairs in a serialization context right now, which is too bad in my opinion.

I'd love to see this issue reopened and rethought from a non-JSON restricted perspective.
