### ISSUE TITLE
`OrderedSet.index(of:)`

### ISSUE THREAD

**Issue by lorentey** [apple/swift-collections#88]
The standard `Set` types provides an `index(of:)` method.  Like `Set`, `OrderedSet` also promises that its members are unique, so I believe it would make sense to add `index(of:)` to `OrderedSet`, too -- this will make for clearer code at the point of use than if we only had Collection's `firstIndex(of:)`/`lastIndex(of:)`.

**Comment by lorentey** [comment]
Oops, I forgot `Set.index(of:)` was deprecated. Closing.

**Comment by mdznr** [comment]
To me, there still seems to be value of having an `index(of:)` for `OrderedSet` instead of calling `firstIndex(of:)` or `lastIndex(of:)` since it clarifies at the call site that there is only ever one index (or `nil`) for a particular element. Calling `firstIndex(of:)` makes it seem like there could be multiple.
